# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.12.2
mod_version=1.0.0
forge_version=14.23.5.2855
mod_group=
mod_id=luxuriousmisfortunes
mod_name=Luxurious Misfortunes
mod_archives_name=LuxuriousMisfortunes
mod_author=Kovetz
mod_icon=TEM_logo.png
mod_description=Enjoy the riches of forgotten times while your soul cracks with curses
mod_credits=
